### ISSUE TITLE
build broken with vis-network 5.2.4

### ISSUE THREAD

**Issue by ydg2018** [visjs/vis-network#82]
After updating vis-network to 5.2.4 in my angular project i keep getting build errors on util.d.ts in the vis-util library inside the node_modules of vis-network.

`ERROR in node_modules/vis-network/node_modules/vis-util/dist/types/util.d.ts(214,61): error TS1005: ',' expected.
node_modules/vis-network/node_modules/vis-util/dist/types/util.d.ts(214,62): error TS1005: ',' expected.
node_modules/vis-network/node_modules/vis-util/dist/types/util.d.ts(215,64): error TS1005: ',' expected.
node_modules/vis-network/node_modules/vis-util/dist/types/util.d.ts(215,65): error TS1005: ',' expected.
node_modules/vis-network/node_modules/vis-util/dist/types/util.d.ts(223,52): error TS1005: ',' expected.
node_modules/vis-network/node_modules/vis-util/dist/types/util.d.ts(223,53): error TS1005: ',' expected.`

I've tried to also install vis-util 1.1.6 in my own project but that did not help.
So how can i fix this problem? or is this something you guys need to fix in the build itself?

**Comment by Thomaash** [comment]
Hi @ydg2018,

I just tested it and it doesn't happen to me. Could you provide an MWE please?

One thing to try is to update TypeScript, we use 3.5.3. Because this looks like the kind of error 3.3 tsc would show with 3.4 project but that's just wild guess.

Thanks.

**Comment by ydg2018** [comment]
ah yes that is a good possibility as our project is still on 3.2.4 because an other library is not updated for the newer versions of typescript. I guess we are coming closer to a time where we need to update typescript and find other solutions for the old library :)
Thanks for the answer.
